# Generated by Django 2.1.7 on 2020-09-22 08:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0002_admin_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='organization_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
