# Generated by Django 2.1.7 on 2020-09-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0003_admin_organization_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='organization_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
