# Generated by Django 2.1.7 on 2020-09-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0006_auto_20200922_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playtimeschedule',
            name='inaday_play_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playtimeschedule',
            name='inaday_play_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
