# Generated by Django 2.1.7 on 2020-09-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0008_auto_20200922_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='playtime',
        ),
        migrations.AddField(
            model_name='playtimeschedule',
            name='video',
            field=models.ManyToManyField(blank=True, null=True, to='device_management.Video'),
        ),
    ]
