# Generated by Django 2.1.7 on 2020-09-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0009_auto_20200922_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playtimeschedule',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='playtime',
            field=models.ManyToManyField(blank=True, null=True, to='device_management.PlayTimeSchedule'),
        ),
        migrations.RemoveField(
            model_name='playtimeschedule',
            name='play_on',
        ),
        migrations.AddField(
            model_name='playtimeschedule',
            name='play_on',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='PlayDay',
        ),
    ]
