# Generated by Django 2.1.7 on 2020-09-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0010_auto_20200923_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='playtime',
            field=models.ManyToManyField(blank=True, null=True, to='device_management.PlayTimeSchedule'),
        ),
    ]
