# Generated by Django 2.1.7 on 2020-10-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0011_device_playtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playtimeschedule',
            name='inaday_gap_required',
        ),
        migrations.RemoveField(
            model_name='playtimeschedule',
            name='inaday_play_from',
        ),
        migrations.RemoveField(
            model_name='playtimeschedule',
            name='inaday_play_to',
        ),
        migrations.RemoveField(
            model_name='playtimeschedule',
            name='play_on',
        ),
        migrations.AddField(
            model_name='playtimeschedule',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playtimeschedule',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
