# Generated by Django 2.1.7 on 2020-10-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0012_auto_20201002_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='playtimeschedule',
            name='video_start_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
