# Generated by Django 2.0.7 on 2020-10-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0013_playtimeschedule_video_start_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
