# Generated by Django 2.0.7 on 2020-11-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0014_auto_20201025_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
