# Generated by Django 2.0.7 on 2020-11-16 14:06

import device_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0016_auto_20201101_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='company_logo',
            field=models.FileField(default=None, upload_to=device_management.models.logo_directory_path),
            preserve_default=False,
        ),
    ]
