# Generated by Django 2.0.7 on 2020-11-20 07:46

import device_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0018_auto_20201116_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to=device_management.models.profile_directory_path),
        ),
    ]
